import { SHARED_LOCK_STALE_MS } from './shared-lock.ts'

export const PROXY_STARTUP_TIMEOUT_MS = 15_000
export const HEALTH_CHECK_TIMEOUT_MS = 2_000
export const HEARTBEAT_TIMEOUT_MS = 2_000
export const TOKEN_PUSH_TIMEOUT_MS = 2_000
export const MODEL_REFRESH_TIMEOUT_MS = 10_000
export const LIFECYCLE_LOCK_MAX_WAIT_MS = SHARED_LOCK_STALE_MS + 250

const HEALTH_CHECKS_PER_RECOVERY = 2
const LIFECYCLE_UPDATES_PER_RECOVERY = 3
const PROXY_COORDINATION_MARGIN_MS = 1_000

export const PROXY_PORT_LOCK_MAX_WAIT_MS =
  HEALTH_CHECK_TIMEOUT_MS * HEALTH_CHECKS_PER_RECOVERY +
  TOKEN_PUSH_TIMEOUT_MS +
  HEARTBEAT_TIMEOUT_MS +
  MODEL_REFRESH_TIMEOUT_MS +
  PROXY_STARTUP_TIMEOUT_MS +
  LIFECYCLE_LOCK_MAX_WAIT_MS * LIFECYCLE_UPDATES_PER_RECOVERY +
  SHARED_LOCK_STALE_MS +
  PROXY_COORDINATION_MARGIN_MS
